timeout 1
default postmarketOS
menu title boot prev kernel

label postmarketOS
	kernel /vmlinuz
	fdtdir /
	initrd /initramfs
	append quiet splash plymouth.ignore-serial-consoles plymouth.prefer-fbcon pmos_boot_uuid=auto pmos_root_uuid=auto pmos_rootfsopts=defaults
